### ISSUE TITLE
Suggestion to improve argument parsing

### ISSUE THREAD

**Issue by Gers2017** [usefulmove/comp#6]
Hi @usefulmove I noticed that you're parsing the arguments by yourself.
I'm referring to `src/comp.rs`
```rs
  let mut args: Vec<String> = env::args().collect();
  // ...
  if args.len() <= 1 {
    args.push("help".to_string());
  }
  // ...
```
As a suggestion please take a look at this [crate](https://crates.io/crates/argh), which takes care of argument parsing, (lightweight in comparison to clap)

This is only a suggestion, you're free to dismiss it 😁. Hopefully this will help you with future projects!

**Comment by usefulmove** [comment]
Thank you @Gers2017! I'll check out the **argh** crate.
